### ISSUE TITLE
Add folder-based approach

### ISSUE THREAD

**Issue by nicojs** [slara/generator-reveal#78]
I would like to add the possibility to get rit of the metadata keeping in the `list.json`. I would like to suggest to just order the slides by alphabet. 

I usually order my slides like this:

```
/1-chapter1/0-chapter1-introduction.md
/1-chapter1/1-slide1.md
/1-chapter1/2-slide2.html
/2-chapter2/0-chapter2-introduction.md
/2-chapter2/1-chapter2-slide1.md
/3-chapter3-one-slide-only.md
```

Maintaining my list.json file becomes tedious to say the least.

I'm a big fan of the generator-reveal, just this one thing is bothering me. If you agree, i can do a PR. How would you suggest it would work? Just use the list.json if its there, otherwise do the folder ordering mechanism?

**Comment by janraasch** [comment]
Hi @nicojs, thank you for the suggestion.

Here is my take on it:

Essentially you are taking the metadata from `list.json` and putting it into the `filename` (*and* the `file` in case you need to specify attributes like `style` and `data`). I suppose this is a matter of taste, but I think the nice part about `list.json` is that the `*.md` files used in the presentation can be totally clean with respect to the presentation logic of the `reveal` framework. They can be simple markdown files with filenames that respresent their content and not their position in the presentation.

Of course we could always add options, but looking at https://github.com/slara/generator-reveal/blob/master/app/index.coffee we already have `7` options and I would rather have less options than more. So I would rather then switch completely to another approach instead of adding yet another configuration variable; but for my taste (as I outlined above) the `list.json` version is a nicer fit to separate mere content from presentation logic.

What do you think @slara?

**Comment by nicojs** [comment]
@janraasch  Good point about the specifying the attributes like style and data. I would also opt for not using the content of a file for the presentation logic. But i don't see the 7 options that you are talking about.

My filenames also represent their content, but i number them so i can easily see the order of my slides in my file explorer.

**Comment by janraasch** [comment]
The `prompts` array has a length of `7`, see https://github.com/slara/generator-reveal/blob/master/app/index.coffee#L32.

**Comment by nicojs** [comment]
Ah ok, i thought you meant that there were already 7 ways of configuring the slides order. The way i see it, there will not be a new option: if the `lists.json` file is there, it will be used, if its not there it won't be used.

**Comment by slara** [comment]
Hi @nicojs and @janraasch,

thanks @nicojs for your suggestion.

As @janraasch said, I think we could have a problem with slide attributes configuration. I can't see how we could set this attributes without altering the markdown files. 

Having folder-based slide sorting and a `list.json` file with the configuration at the same time could create a lot of confusion. 

Another problem that I see is that if you need to add one slide in the middle of your presentation, you will need to change every filename after that slide.

**Comment by janraasch** [comment]
Very good points, @slara.

@nicojs: 

> The way i see it, there will not be a new option: if the lists.json file is there, it will be used

The problem is that all our `yo reveal:slide "Slide Title"` commands also rely on the `list.json` file, so the user has to tell our generater whether to scaffold it out our not. Thus we would need to prompt the user when first running `yo reveal "My Presentation"`.

I figure, you can easily adjust the code in the generated `Gruntfile.coffee` of your presentation (see `https://github.com/slara/generator-reveal/blob/master/app/templates/_Gruntfile.coffee#L118`) to create the `slides Array` in a way that fits your needs, @nicojs. 

So we will not pull this into the generator itself as we try to cover the most common use case; and then the great thing about generators after all is that it gives you a quick start, *but* you can adjust everything to your own individual needs after that.

**Comment by nicojs** [comment]
@slara 
> So we will not pull this into the generator itself as we try to cover the most common use case; and then the great thing about generators after all is that it gives you a quick start, but you can adjust everything to your own individual needs after that. 

Fair enough.
